version: 2
updates:
  # TODO: Disabled for now; maybe enable later
  # - package-ecosystem: "gradle"
  #  directory: "/"
  #  schedule:
  #    interval: "monthly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
