name: build

on: [push, pull_request]

jobs:
  build:
    name: Java ${{ matrix.java-version }} on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java-version: [ 8, 11, 16 ]

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java-version }}
          cache: 'gradle'

      - name: Build and test on Ubuntu and macOS
        if: ${{ matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest' }}
        run: ./gradlew check

      - name: Build and test on Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: gradlew.bat check
        shell: cmd

# TODO: Don't update, just check for differences and create diff (but don't let workflow fail)
  update-accuracy-reports:
    name: Update accuracy reports
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Store or retrieve Gradle caches
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Update accuracy reports
        run: ./.github/workflow-scripts/update-accuracy-reports.sh
