name: release

on:
  push:
    tags:
      - v*

permissions:
  contents: write # to fetch code and create release


jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
          cache: 'gradle'

      - name: Get tag version
        id: get_version
        run: |
          # Remove leading `v` from short ref name
          version="${GITHUB_REF_NAME#v}"
          echo "version=${version}" >> $GITHUB_OUTPUT
          echo "Version: ${version}"

      - name: Create release artifacts
        run: ./gradlew jar sourcesJar jarWithDependencies dokkaJavadocJar dokkaHtmlJar

      - name: Create release and upload artifacts
        uses: softprops/action-gh-release@v1
        with:
          name: Tiny Lingua ${{ steps.get_version.outputs.version }}
          files: build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
